name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        user: actions/checkout@v4
      - name: Cypress run
        user: cypress-io/github-action@v6